// src/routes/auth/login/+page.svelte
<script lang="ts">
    import { enhance } from '$app/forms';

    let email = $state('');
    let password = $state('');
    let loading = $state(false);
    let error = $state('');
    let showPassword = $state(false);
</script>

<main class="auth-page">
    <div class="auth-container">
        <div class="auth-header">
            <a href="/" class="auth-logo">PreFlight<span class="dot">.</span></a>
            <h1>Welcome back</h1>
            <p>Log in to view your reviews.</p>
        </div>

        <form
            method="POST"
            action="?/login"
            use:enhance={() => {
                loading = true;
                error = '';
                return async ({ result }) => {
                    loading = false;
                    if (result.type === 'failure') {
                        error = (result.data?.message as string) ?? 'Invalid email or password.';
                    } else if (result.type === 'redirect') {
                        window.location.href = result.location;
                    }
                };
            }}
            class="auth-form"
        >
            <div class="form-group">
                <label for="email" class="form-label">Email</label>
                <input
                    id="email"
                    type="email"
                    name="email"
                    class="input"
                    bind:value={email}
                    placeholder="you@example.com"
                    required
                    disabled={loading}
                />
            </div>

            <div class="form-group">
                <label for="password" class="form-label">Password</label>
                <div class="input-wrapper">
                    <input
                        id="password"
                        type={showPassword ? 'text' : 'password'}
                        name="password"
                        class="input input-password"
                        bind:value={password}
                        placeholder="••••••••"
                        required
                        disabled={loading}
                    />
                    <button
                        type="button"
                        class="eye-toggle"
                        onclick={() => showPassword = !showPassword}
                        aria-label={showPassword ? 'Hide password' : 'Show password'}
                        tabindex="-1"
                    >
                        {#if showPassword}
                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94"/>
                                <path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19"/>
                                <path d="M14.12 14.12a3 3 0 1 1-4.24-4.24"/>
                                <line x1="1" y1="1" x2="23" y2="23"/>
                            </svg>
                        {:else}
                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
                                <circle cx="12" cy="12" r="3"/>
                            </svg>
                        {/if}
                    </button>
                </div>
            </div>

            {#if error}
                <p class="error-msg">{error}</p>
            {/if}

            <button type="submit" class="btn btn-primary btn-lg btn-full" disabled={loading}>
                {loading ? 'Logging in...' : 'Log in'}
            </button>
        </form>

        <p class="auth-switch">
            Don't have an account? <a href="/auth/signup">Sign up</a>
        </p>
    </div>
</main>

<style>
    .auth-page {
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 24px;
    }

    .auth-container {
        width: 100%;
        max-width: 360px;
    }

    .auth-header {
        margin-bottom: 32px;
    }

    .auth-logo {
        font-family: 'Outfit', sans-serif;
        font-size: 18px;
        font-weight: 700;
        display: block;
        margin-bottom: 24px;
    }

    .dot {
        color: var(--accent);
        font-weight: 800;
    }

    h1 {
        font-size: 24px;
        margin-bottom: 6px;
    }

    .auth-header p {
        font-size: 14px;
        color: var(--gray-300);
    }

    .auth-form {
        margin-bottom: 24px;
    }

    .input-wrapper {
        position: relative;
    }

    .input-password {
        padding-right: 44px;
    }

    .eye-toggle {
        position: absolute;
        right: 12px;
        top: 50%;
        transform: translateY(-50%);
        background: none;
        border: none;
        color: var(--gray-500);
        cursor: pointer;
        padding: 4px;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: color var(--duration-fast);
    }

    .eye-toggle:hover {
        color: var(--gray-300);
    }

    .error-msg {
        font-size: 13px;
        color: var(--status-failed-fg);
        margin-bottom: 16px;
        padding: 10px 14px;
        background: var(--status-failed-bg);
        border-radius: var(--radius-md);
    }

    .btn-full {
        width: 100%;
        margin-top: 8px;
    }

    .auth-switch {
        font-size: 13px;
        color: var(--gray-500);
        text-align: center;
    }

    .auth-switch a {
        color: var(--accent);
        font-weight: 500;
        transition: color var(--duration-fast);
    }

    .auth-switch a:hover {
        color: var(--accent-hover);
    }
</style>

// src/app/auth/login/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { login } from '../actions'
import { ArrowLeft, Eye, EyeOff } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

export default function LoginPage() {
    const router = useRouter()
    const [showPassword, setShowPassword] = useState(false)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [checkingAuth, setCheckingAuth] = useState(true)

    // Redirect if already logged in
    useEffect(() => {
        const checkAuth = async () => {
            const supabase = createClient()
            const { data: { user } } = await supabase.auth.getUser()
            if (user) {
                router.push('/dashboard')
            } else {
                setCheckingAuth(false)
            }
        }
        checkAuth()
    }, [router])

    async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault()
        setLoading(true)
        setError(null)

        const formData = new FormData(e.currentTarget)
        const result = await login(formData)

        if (result?.error) {
            setError(result.error)
            setLoading(false)
        }
    }

    // Show a loading state while checking auth
    if (checkingAuth) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-black">
                <div className="text-gray-500">Loading...</div>
            </div>
        )
    }

    return (
        <div className="min-h-screen flex items-center justify-center bg-black px-6">
            <div className="w-full max-w-sm">
                <Link href="/" className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-white transition-colors mb-8 group">
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    Back to site
                </Link>

                <div className="vercel-card">
                    <h1 className="text-2xl font-bold tracking-tighter mb-2">Welcome back</h1>
                    <p className="text-sm text-gray-500 font-light mb-8">Log in to your Preflight account</p>

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div className="space-y-2">
                            <label className="text-xs font-medium text-gray-400 uppercase tracking-widest">Email</label>
                            <input
                                type="email"
                                name="email"
                                required
                                className="w-full bg-black border border-border rounded-md px-3 py-2 text-sm focus:border-white transition-colors outline-none"
                                placeholder="you@example.com"
                            />
                        </div>

                        <div className="space-y-2">
                            <div className="flex justify-between items-center">
                                <label className="text-xs font-medium text-gray-400 uppercase tracking-widest">Password</label>
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="text-gray-500 hover:text-white transition-colors"
                                >
                                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                                </button>
                            </div>
                            <input
                                type={showPassword ? "text" : "password"}
                                name="password"
                                required
                                className="w-full bg-black border border-border rounded-md px-3 py-2 text-sm focus:border-white transition-colors outline-none"
                                placeholder="••••••••"
                            />
                        </div>

                        {error && (
                            <div className="text-xs text-red-500 bg-red-500/10 border border-red-500/20 p-3 rounded-md">
                                {error}
                            </div>
                        )}

                        <button
                            type="submit"
                            disabled={loading}
                            className="vercel-btn-primary w-full disabled:opacity-50"
                        >
                            {loading ? "Logging in..." : "Log In"}
                        </button>
                    </form>
                </div>

                <p className="text-center mt-8 text-sm text-gray-500 font-light">
                    Don't have an account?{' '}
                    <Link href="/auth/signup" className="text-white hover:underline underline-offset-4">
                        Sign up
                    </Link>
                </p>
            </div>
        </div>
    );
}
