// src/lib/components/ASCConnectModal.svelte
<script lang="ts">
    /**
     * ASCConnectModal — Optional App Store Connect integration
     *
     * Three-step flow:
     * 1. Enter Key ID, Issuer ID, upload .p8 file
     * 2. Validate → show app list
     * 3. Select app → auto-fill form
     */

    let {
        open = $bindable(false),
        onAutofill,
    }: {
        open: boolean;
        onAutofill: (data: Record<string, string>) => void;
    } = $props();

    let modalStep = $state(1);
    let connecting = $state(false);
    let loading = $state(false);
    let error = $state('');

    // Step 1: Credentials
    let keyId = $state('');
    let issuerId = $state('');
    let privateKeyContent = $state('');
    let fileName = $state('');

    // Step 2: App list
    let apps: Array<{ id: string; name: string; bundleId: string }> = $state([]);
    let teamName = $state('');

    // Step 3: Selected app
    let selectedAppId = $state('');
    let autofilling = $state(false);

    function handleFileUpload(e: Event) {
        const input = e.target as HTMLInputElement;
        const file = input.files?.[0];
        if (!file) return;

        fileName = file.name;
        const reader = new FileReader();
        reader.onload = () => {
            privateKeyContent = reader.result as string;
        };
        reader.readAsText(file);
    }

    async function connect() {
        if (!keyId || !issuerId || !privateKeyContent) {
            error = 'Please fill in all fields and upload your .p8 key file.';
            return;
        }

        connecting = true;
        error = '';

        try {
            const res = await fetch('/api/asc/connect', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    keyId,
                    issuerId,
                    privateKey: privateKeyContent,
                }),
            });

            if (!res.ok) {
                const data = await res.json().catch(() => ({}));
                throw new Error(data.message || `Connection failed (${res.status})`);
            }

            const data = await res.json();
            apps = data.apps || [];
            teamName = data.teamName || 'Connected';
            modalStep = 2;
        } catch (err: unknown) {
            error = err instanceof Error ? err.message : 'Failed to connect';
        } finally {
            connecting = false;
        }
    }

    async function selectApp(appId: string) {
        selectedAppId = appId;
        autofilling = true;
        error = '';

        try {
            const res = await fetch('/api/asc/autofill', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ appId }),
            });

            if (!res.ok) {
                const data = await res.json().catch(() => ({}));
                throw new Error(data.message || 'Failed to fetch app data');
            }

            const { data } = await res.json();
            onAutofill(data);
            close();
        } catch (err: unknown) {
            error = err instanceof Error ? err.message : 'Failed to fetch app data';
        } finally {
            autofilling = false;
        }
    }

    function close() {
        open = false;
        // Reset state for next open
        setTimeout(() => {
            modalStep = 1;
            error = '';
            connecting = false;
            autofilling = false;
        }, 300);
    }

    function handleBackdropClick(e: MouseEvent) {
        if ((e.target as HTMLElement).classList.contains('modal-backdrop')) {
            close();
        }
    }
</script>

{#if open}
<div class="modal-backdrop" onclick={handleBackdropClick} role="presentation">
    <div class="modal-container">
        <button class="modal-close" onclick={close} aria-label="Close">×</button>

        {#if modalStep === 1}
            <!-- Step 1: Enter Credentials -->
            <div class="modal-header">
                <div class="modal-icon">🔗</div>
                <h2>Connect App Store Connect</h2>
                <p class="modal-subtitle">Auto-fill your submission form with data from Apple's API. This is optional.</p>
            </div>

            <div class="modal-body">
                {#if error}
                    <div class="error-banner">{error}</div>
                {/if}

                <div class="form-group">
                    <label for="asc-key-id">Key ID</label>
                    <input
                        type="text"
                        id="asc-key-id"
                        bind:value={keyId}
                        placeholder="e.g. ABC1234DEF"
                        class="input"
                    />
                    <span class="help-text">Found in App Store Connect &gt; Users &gt; Integrations &gt; Keys</span>
                </div>

                <div class="form-group">
                    <label for="asc-issuer-id">Issuer ID</label>
                    <input
                        type="text"
                        id="asc-issuer-id"
                        bind:value={issuerId}
                        placeholder="e.g. 12345678-1234-1234-1234-123456789012"
                        class="input"
                    />
                    <span class="help-text">Shown at the top of the Keys page</span>
                </div>

                <div class="form-group">
                    <label for="asc-p8">Private Key (.p8 file)</label>
                    <div class="file-upload-area">
                        <input
                            type="file"
                            id="asc-p8"
                            accept=".p8,.pem"
                            onchange={handleFileUpload}
                            class="file-input-hidden"
                        />
                        <label for="asc-p8" class="file-upload-label">
                            {#if fileName}
                                <span class="file-name">✓ {fileName}</span>
                            {:else}
                                <span class="file-prompt">Choose .p8 file or drag here</span>
                            {/if}
                        </label>
                    </div>
                    <span class="help-text">The .p8 key file downloaded when you created the API key</span>
                </div>
            </div>

            <div class="modal-footer">
                <button class="btn btn-secondary" onclick={close}>Cancel</button>
                <button
                    class="btn btn-primary"
                    onclick={connect}
                    disabled={connecting || !keyId || !issuerId || !privateKeyContent}
                >
                    {connecting ? 'Connecting...' : 'Connect'}
                </button>
            </div>

        {:else if modalStep === 2}
            <!-- Step 2: Select App -->
            <div class="modal-header">
                <div class="modal-icon">✅</div>
                <h2>Connected to {teamName}</h2>
                <p class="modal-subtitle">Select the app you want to submit for review.</p>
            </div>

            <div class="modal-body">
                {#if error}
                    <div class="error-banner">{error}</div>
                {/if}

                <div class="app-list">
                    {#each apps as app}
                        <button
                            class="app-card"
                            class:selected={selectedAppId === app.id}
                            onclick={() => selectApp(app.id)}
                            disabled={autofilling}
                        >
                            <div class="app-info">
                                <span class="app-name">{app.name}</span>
                                <span class="app-bundle">{app.bundleId}</span>
                            </div>
                            {#if autofilling && selectedAppId === app.id}
                                <span class="loading-dot">Loading...</span>
                            {:else}
                                <span class="select-arrow">→</span>
                            {/if}
                        </button>
                    {/each}
                </div>

                {#if apps.length === 0}
                    <p class="empty-state">No apps found. Make sure your API key has access to at least one app.</p>
                {/if}
            </div>

            <div class="modal-footer">
                <button class="btn btn-secondary" onclick={() => { modalStep = 1; error = ''; }}>Back</button>
                <button class="btn btn-secondary" onclick={close}>Cancel</button>
            </div>
        {/if}
    </div>
</div>
{/if}

<style>
    .modal-backdrop {
        position: fixed;
        inset: 0;
        background: rgba(0, 0, 0, 0.6);
        backdrop-filter: blur(4px);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
        padding: 1rem;
    }

    .modal-container {
        background: var(--surface-1, #1a1a2e);
        border: 1px solid var(--border, rgba(255, 255, 255, 0.1));
        border-radius: 16px;
        width: 100%;
        max-width: 520px;
        max-height: 85vh;
        overflow-y: auto;
        position: relative;
    }

    .modal-close {
        position: absolute;
        top: 12px;
        right: 12px;
        background: none;
        border: none;
        color: var(--text-muted, #888);
        font-size: 1.5rem;
        cursor: pointer;
        padding: 4px 8px;
        border-radius: 8px;
        transition: background 0.2s;
    }

    .modal-close:hover {
        background: rgba(255, 255, 255, 0.1);
    }

    .modal-header {
        padding: 2rem 2rem 0.5rem;
        text-align: center;
    }

    .modal-icon {
        font-size: 2.5rem;
        margin-bottom: 0.75rem;
    }

    .modal-header h2 {
        font-size: 1.25rem;
        font-weight: 600;
        color: var(--text-primary, #fff);
        margin: 0 0 0.5rem;
    }

    .modal-subtitle {
        color: var(--text-muted, #888);
        font-size: 0.875rem;
        margin: 0;
        line-height: 1.5;
    }

    .modal-body {
        padding: 1.5rem 2rem;
    }

    .modal-footer {
        padding: 1rem 2rem 1.5rem;
        display: flex;
        gap: 0.75rem;
        justify-content: flex-end;
    }

    .form-group {
        margin-bottom: 1.25rem;
    }

    .form-group label {
        display: block;
        font-size: 0.875rem;
        font-weight: 500;
        color: var(--text-primary, #fff);
        margin-bottom: 0.375rem;
    }

    .input {
        width: 100%;
        padding: 0.625rem 0.75rem;
        background: var(--surface-2, rgba(255, 255, 255, 0.05));
        border: 1px solid var(--border, rgba(255, 255, 255, 0.1));
        border-radius: 8px;
        color: var(--text-primary, #fff);
        font-size: 0.875rem;
        transition: border-color 0.2s;
    }

    .input:focus {
        outline: none;
        border-color: var(--accent, #6366f1);
    }

    .input::placeholder {
        color: var(--text-muted, #555);
    }

    .help-text {
        display: block;
        font-size: 0.75rem;
        color: var(--text-muted, #666);
        margin-top: 0.25rem;
    }

    .file-upload-area {
        position: relative;
    }

    .file-input-hidden {
        position: absolute;
        inset: 0;
        opacity: 0;
        cursor: pointer;
    }

    .file-upload-label {
        display: block;
        padding: 1rem;
        background: var(--surface-2, rgba(255, 255, 255, 0.05));
        border: 2px dashed var(--border, rgba(255, 255, 255, 0.15));
        border-radius: 8px;
        text-align: center;
        cursor: pointer;
        transition: border-color 0.2s, background 0.2s;
    }

    .file-upload-label:hover {
        border-color: var(--accent, #6366f1);
        background: rgba(99, 102, 241, 0.05);
    }

    .file-prompt {
        color: var(--text-muted, #888);
        font-size: 0.875rem;
    }

    .file-name {
        color: var(--success, #22c55e);
        font-size: 0.875rem;
    }

    .error-banner {
        background: rgba(239, 68, 68, 0.1);
        border: 1px solid rgba(239, 68, 68, 0.3);
        color: #ef4444;
        padding: 0.75rem 1rem;
        border-radius: 8px;
        font-size: 0.875rem;
        margin-bottom: 1rem;
    }

    .app-list {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }

    .app-card {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0.875rem 1rem;
        background: var(--surface-2, rgba(255, 255, 255, 0.05));
        border: 1px solid var(--border, rgba(255, 255, 255, 0.1));
        border-radius: 10px;
        cursor: pointer;
        transition: all 0.2s;
        width: 100%;
        text-align: left;
        color: var(--text-primary, #fff);
    }

    .app-card:hover:not(:disabled) {
        border-color: var(--accent, #6366f1);
        background: rgba(99, 102, 241, 0.08);
    }

    .app-card:disabled {
        opacity: 0.7;
        cursor: wait;
    }

    .app-card.selected {
        border-color: var(--accent, #6366f1);
    }

    .app-info {
        display: flex;
        flex-direction: column;
        gap: 0.125rem;
    }

    .app-name {
        font-weight: 500;
        font-size: 0.9375rem;
    }

    .app-bundle {
        font-size: 0.75rem;
        color: var(--text-muted, #888);
    }

    .select-arrow {
        font-size: 1.25rem;
        color: var(--text-muted, #666);
    }

    .loading-dot {
        font-size: 0.75rem;
        color: var(--accent, #6366f1);
    }

    .empty-state {
        text-align: center;
        color: var(--text-muted, #888);
        font-size: 0.875rem;
        padding: 2rem 0;
    }

    .btn {
        padding: 0.625rem 1.25rem;
        border-radius: 8px;
        font-size: 0.875rem;
        font-weight: 500;
        cursor: pointer;
        border: none;
        transition: all 0.2s;
    }

    .btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .btn-primary {
        background: var(--accent, #6366f1);
        color: white;
    }

    .btn-primary:hover:not(:disabled) {
        background: var(--accent-hover, #5558e8);
    }

    .btn-secondary {
        background: transparent;
        border: 1px solid var(--border, rgba(255, 255, 255, 0.1));
        color: var(--text-primary, #fff);
    }

    .btn-secondary:hover {
        background: rgba(255, 255, 255, 0.05);
    }
</style>

// packages/web/src/components/ASCConnectModal.tsx
'use client'

import { useState } from 'react'
import { X, Check, Loader2, Link as LinkIcon, Smartphone, ArrowRight } from 'lucide-react'
import { cn } from '@/components/ui/status'

interface ASCApp {
    id: string
    name: string
    bundleId: string
}

interface ASCConnectModalProps {
    isOpen: boolean
    onClose: () => void
    onAutofill: (data: Record<string, unknown>) => void
}

export function ASCConnectModal({ isOpen, onClose, onAutofill }: ASCConnectModalProps) {
    const [modalStep, setModalStep] = useState(1)
    const [connecting, setConnecting] = useState(false)
    const [autofilling, setAutofilling] = useState(false)
    const [error, setError] = useState('')

    // Step 1: Credentials
    const [keyId, setKeyId] = useState('')
    const [issuerId, setIssuerId] = useState('')
    const [privateKeyContent, setPrivateKeyContent] = useState('')
    const [fileName, setFileName] = useState('')

    // Step 2: App list
    const [apps, setApps] = useState<ASCApp[]>([])
    const [teamName, setTeamName] = useState('')
    const [selectedAppId, setSelectedAppId] = useState('')

    if (!isOpen) return null

    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (!file) return

        setFileName(file.name)
        const reader = new FileReader()
        reader.onload = () => {
            setPrivateKeyContent(reader.result as string)
        }
        reader.readAsText(file)
    }

    const handleConnect = async () => {
        if (!keyId || !issuerId || !privateKeyContent) {
            setError('Please fill in all fields and upload your .p8 key file.')
            return
        }

        setConnecting(true)
        setError('')

        try {
            const res = await fetch('/api/asc/connect', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ keyId, issuerId, privateKey: privateKeyContent }),
            })

            if (!res.ok) {
                const data = await res.json().catch(() => ({}))
                throw new Error(data.message || `Connection failed (${res.status})`)
            }

            const data = await res.json()
            setApps(data.apps || [])
            setTeamName(data.teamName || 'Connected')
            setModalStep(2)
        } catch (err) {
            const message = err instanceof Error ? err.message : 'Failed to connect'
            setError(message)
        } finally {
            setConnecting(false)
        }
    }

    const handleSelectApp = async (appId: string) => {
        setSelectedAppId(appId)
        setAutofilling(true)
        setError('')

        try {
            const res = await fetch('/api/asc/autofill', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ appId }),
            })

            if (!res.ok) {
                const data = await res.json().catch(() => ({}))
                throw new Error(data.message || 'Failed to fetch app data')
            }

            const { data } = await res.json()
            onAutofill(data)
            onClose()
        } catch (err) {
            const message = err instanceof Error ? err.message : 'Failed to fetch app data'
            setError(message)
        } finally {
            setAutofilling(false)
        }
    }

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="vercel-card max-w-lg w-full relative overflow-hidden shadow-2xl border-white/10">
                <button
                    onClick={onClose}
                    className="absolute top-4 right-4 text-gray-500 hover:text-white transition-colors"
                >
                    <X className="w-5 h-5" />
                </button>

                {modalStep === 1 ? (
                    <div className="p-8">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center">
                                <LinkIcon className="w-5 h-5 text-white" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold tracking-tight">Connect App Store Connect</h2>
                                <p className="text-sm text-gray-500 font-light">Import metadata directly from Apple</p>
                            </div>
                        </div>

                        {error && (
                            <div className="mb-6 p-3 rounded-md bg-red-500/10 border border-red-500/20 text-red-500 text-xs">
                                {error}
                            </div>
                        )}

                        <div className="space-y-4">
                            <div className="space-y-2">
                                <label className="text-[10px] font-bold tracking-widest text-gray-500 uppercase">Key ID</label>
                                <input
                                    value={keyId}
                                    onChange={e => setKeyId(e.target.value)}
                                    placeholder="e.g. ABC1234DEF"
                                    className="w-full bg-black border border-white/10 rounded-md px-3 py-2 text-sm outline-none focus:border-white transition-colors"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-[10px] font-bold tracking-widest text-gray-500 uppercase">Issuer ID</label>
                                <input
                                    value={issuerId}
                                    onChange={e => setIssuerId(e.target.value)}
                                    placeholder="e.g. 12345678-..."
                                    className="w-full bg-black border border-white/10 rounded-md px-3 py-2 text-sm outline-none focus:border-white transition-colors"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-[10px] font-bold tracking-widest text-gray-500 uppercase">Private Key (.p8)</label>
                                <label className="block border-2 border-dashed border-white/5 rounded-md p-6 text-center hover:bg-white/5 cursor-pointer transition-colors group">
                                    <input type="file" accept=".p8" onChange={handleFileUpload} className="hidden" />
                                    {fileName ? (
                                        <div className="flex items-center justify-center gap-2 text-green-500 text-sm">
                                            <Check className="w-4 h-4" /> {fileName}
                                        </div>
                                    ) : (
                                        <>
                                            <div className="text-sm text-gray-500 group-hover:text-gray-300">Click to upload .p8 key file</div>
                                            <div className="text-[10px] text-gray-600 mt-1">Found in App Store Connect {'>'} Users {'>'} Keys</div>
                                        </>
                                    )}
                                </label>
                            </div>
                        </div>

                        <div className="flex gap-3 mt-8">
                            <button onClick={onClose} className="vercel-btn-secondary flex-1">Cancel</button>
                            <button
                                onClick={handleConnect}
                                disabled={connecting || !keyId || !issuerId || !privateKeyContent}
                                className="vercel-btn-primary flex-1 flex items-center justify-center gap-2"
                            >
                                {connecting ? <Loader2 className="w-4 h-4 animate-spin" /> : "Connect"}
                            </button>
                        </div>
                    </div>
                ) : (
                    <div className="p-8">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="w-10 h-10 rounded-full bg-green-500/10 flex items-center justify-center">
                                <Check className="w-5 h-5 text-green-500" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold tracking-tight">Connected to {teamName}</h2>
                                <p className="text-sm text-gray-500 font-light">Select an app to import metadata</p>
                            </div>
                        </div>

                        <div className="space-y-2 max-h-[300px] overflow-y-auto pr-2 custom-scrollbar">
                            {apps.map(app => (
                                <button
                                    key={app.id}
                                    onClick={() => handleSelectApp(app.id)}
                                    disabled={autofilling}
                                    className={cn(
                                        "w-full flex items-center justify-between p-4 rounded-md border border-white/5 hover:border-white/20 transition-all text-left group",
                                        selectedAppId === app.id && "bg-white/5 border-white/20"
                                    )}
                                >
                                    <div className="flex items-center gap-3">
                                        <div className="w-8 h-8 rounded bg-white/5 flex items-center justify-center group-hover:bg-white/10">
                                            <Smartphone className="w-4 h-4 text-gray-400" />
                                        </div>
                                        <div>
                                            <div className="text-sm font-medium text-white">{app.name}</div>
                                            <div className="text-[10px] text-gray-500 font-mono uppercase tracking-wider">{app.bundleId}</div>
                                        </div>
                                    </div>
                                    {autofilling && selectedAppId === app.id ? (
                                        <Loader2 className="w-4 h-4 animate-spin text-gray-500" />
                                    ) : (
                                        <ArrowRight className="w-4 h-4 text-gray-600 group-hover:text-white transition-colors" />
                                    )}
                                </button>
                            ))}
                        </div>

                        <div className="mt-8 flex gap-3">
                            <button onClick={() => setModalStep(1)} className="vercel-btn-secondary flex-1">Back</button>
                            <button onClick={onClose} className="vercel-btn-secondary flex-1">Close</button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    )
}
