// src/routes/dashboard/+page.svelte
<script lang="ts">
    import CockpitPanel from "$lib/components/CockpitPanel.svelte";
    import StatusLight from "$lib/components/StatusLight.svelte";

    let { data } = $props();

    type Submission = {
        id: string;
        app_name: string;
        review_type: "quick" | "full";
        status:
            | "draft"
            | "paid"
            | "queued"
            | "analyzing"
            | "complete"
            | "failed";
        created_at: string;
    };

    let submissions: Submission[] = $derived(data.submissions ?? []);
    let credits: number = $derived(data.credits ?? 0);

    function formatDate(dateStr: string): string {
        const date = new Date(dateStr);
        return date.toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
        });
    }

    function isClickable(status: string): boolean {
        return status === "complete";
    }

    function mapStatus(
        status: string,
    ): "neutral" | "ready" | "processing" | "warning" | "critical" {
        switch (status) {
            case "complete":
                return "ready";
            case "analyzing":
                return "processing";
            case "failed":
                return "critical";
            case "queued":
                return "warning";
            case "paid":
                return "warning";
            default:
                return "neutral";
        }
    }
</script>

<div class="dashboard container">
    <header class="dash-header">
        <h1>Your Reviews</h1>
        <div class="header-actions">
            <a href="/pricing" class="btn btn-secondary btn-sm">Buy Credits</a>
            <a href="/submit" class="btn btn-primary">
                <span class="plus">+</span> New Review
            </a>
        </div>
    </header>

    {#if submissions.length === 0}
        <CockpitPanel class="empty-state">
            <div class="empty-icon">
                <svg
                    width="56"
                    height="56"
                    viewBox="0 0 56 56"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <rect
                        x="10"
                        y="8"
                        width="28"
                        height="34"
                        rx="6"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-opacity="0.6"
                    />
                    <path
                        d="M18 18h12M18 24h8"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-opacity="0.4"
                    />
                    <circle
                        cx="38"
                        cy="36"
                        r="10"
                        stroke="currentColor"
                        stroke-width="1.5"
                    />
                    <path
                        d="M43 41l4 4"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                    />
                </svg>
            </div>
            <h2>No reviews yet</h2>
            <p>
                Submit your first app and get a detailed compliance report
                before you hit Send.
            </p>
            <a href="/submit" class="btn btn-primary btn-lg"
                >Start Your First Review</a
            >
        </CockpitPanel>
    {:else}
        <div class="submissions-list">
            {#each submissions as sub (sub.id)}
                {@const clickable = isClickable(sub.status)}
                <a
                    href={clickable ? `/report/${sub.id}` : undefined}
                    class="submission-link"
                    class:clickable
                    role={clickable ? "link" : "article"}
                    tabindex={clickable ? 0 : -1}
                >
                    <CockpitPanel class="submission-card" active={clickable}>
                        <div class="card-left">
                            <span class="app-name">{sub.app_name}</span>
                            <span class="card-meta">
                                <span
                                    class="review-type"
                                    class:full={sub.review_type === "full"}
                                >
                                    {sub.review_type === "full"
                                        ? "Full"
                                        : "Quick"}
                                </span>
                                {formatDate(sub.created_at)}
                            </span>
                        </div>
                        <div class="card-right">
                            <StatusLight
                                status={mapStatus(sub.status)}
                                label={sub.status}
                                pulse={sub.status === "analyzing" ||
                                    sub.status === "queued"}
                            />
                        </div>
                    </CockpitPanel>
                </a>
            {/each}
        </div>
    {/if}
</div>

<style>
    .dashboard {
        padding-top: 40px;
        padding-bottom: 64px;
    }

    .dash-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 32px;
        gap: 1.5rem;
    }

    .dash-header h1 {
        font-size: 28px;
        letter-spacing: -0.03em;
    }

    .header-actions {
        display: flex;
        align-items: center;
        gap: 1rem;
    }

    .credit-badge {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.5rem 1rem;
        background: rgba(212, 168, 83, 0.08);
        border: 1px solid rgba(212, 168, 83, 0.2);
        border-radius: 8px;
    }

    .credit-icon {
        font-size: 1.25rem;
    }

    .credit-amount {
        font-family: "Outfit", sans-serif;
        font-size: 1.25rem;
        font-weight: 700;
        color: var(--accent);
    }

    .credit-label {
        font-size: 0.85rem;
        color: var(--gray-400);
    }

    .btn-sm {
        padding: 0.5rem 1rem;
        font-size: 0.875rem;
    }

    .plus {
        font-size: 16px;
        font-weight: 400;
    }

    /* === Empty State === */
    .empty-state {
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        padding: 80px 32px;
        max-width: 320px;
        margin: 0 auto;
        position: relative;
    }

    .empty-state::before {
        content: "";
        position: absolute;
        inset: -40px;
        background: radial-gradient(
            ellipse at 50% 40%,
            rgba(212, 168, 83, 0.03) 0%,
            transparent 60%
        );
        pointer-events: none;
    }

    .empty-icon {
        color: var(--accent);
        margin-bottom: 20px;
        animation: float 3s ease-in-out infinite alternate;
    }

    @keyframes float {
        from {
            transform: translateY(0);
        }
        to {
            transform: translateY(-4px);
        }
    }

    .empty-state h2 {
        font-size: 18px;
        font-weight: 600;
        margin-bottom: 8px;
    }

    .empty-state p {
        font-size: 14px;
        color: var(--gray-300);
        line-height: 1.6;
        margin-bottom: 24px;
    }

    /* === Submissions List === */
    .submissions-list {
        display: flex;
        flex-direction: column;
        gap: 12px;
    }

    .submission-link {
        text-decoration: none;
        color: inherit;
        display: block;
        transition: transform var(--duration-fast) var(--ease-out);
    }

    .submission-link.clickable:hover {
        transform: translateX(2px);
    }

    /* Target inner cockpit panel for layout */
    .submission-link :global(.submission-card) {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 16px 20px;
    }

    .card-left {
        display: flex;
        flex-direction: column;
        gap: 4px;
    }

    .app-name {
        font-family: "Outfit", sans-serif;
        font-size: 15px;
        font-weight: 600;
    }

    .card-meta {
        font-size: 13px;
        color: var(--gray-500);
        display: flex;
        align-items: center;
        gap: 8px;
    }

    .review-type {
        font-family: "Outfit", sans-serif;
        font-size: 11px;
        font-weight: 600;
        text-transform: uppercase;
        background: rgba(168, 165, 160, 0.08);
        color: var(--gray-300);
        padding: 2px 6px;
        border-radius: 4px;
    }

    .review-type.full {
        background: rgba(212, 168, 83, 0.08);
        color: var(--accent);
    }

    .card-right {
        flex-shrink: 0;
    }

    /* Unused Badge styles removed */

    /* === Responsive === */
    @media (max-width: 768px) {
        .dash-header {
            flex-direction: column;
            align-items: stretch;
            gap: 16px;
        }

        .header-actions {
            flex-wrap: wrap;
        }

        .credit-badge {
            flex: 1;
            justify-content: center;
        }

        .dash-header .btn {
            flex: 1;
        }
    }

    @media (max-width: 480px) {
        .header-actions {
            flex-direction: column;
        }

        .dash-header .btn {
            width: 100%;
        }
    }
</style>

// packages/web/src/app/dashboard/page.tsx
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { cn, StatusLight } from "@/components/ui/status";
export const dynamic = "force-dynamic";
import { ArrowRight, Plus } from "lucide-react";
import { ArchiveButton } from "@/components/ArchiveButton";

type Submission = {
    id: string;
    status: string;
    app_name?: string | null;
    created_at: string;
    is_rereviewing?: boolean | null;
};

export default async function DashboardPage() {
    const supabase = await createClient();

    // 1. Get User
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
        redirect("/auth/login");
    }

    // 2. Fetch Submissions (ONLY for current user)
    const { data: submissions, error: submissionsError } = await supabase
        .from("submissions")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false });

    if (submissionsError) {
        console.error("Error fetching submissions:", submissionsError);
    }

    const submissionRows = (submissions ?? []) as Submission[];
    const drafts = submissionRows.filter(s => s.status === 'draft' && !s.is_rereviewing);
    const active = submissionRows.filter(s => s.status !== 'draft' && !s.is_rereviewing);

    function formatDate(dateStr: string): string {
        return new Date(dateStr).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
            hour: "numeric",
            minute: "2-digit",
        });
    }

    function mapStatus(status: string): 'neutral' | 'ready' | 'processing' | 'warning' | 'critical' {
        switch (status) {
            case "complete": return "ready";
            case "analyzing": return "processing";
            case "failed": return "critical";
            case "queued": return "warning";
            case "paid": return "warning";
            default: return "neutral";
        }
    }

    function SubmissionCard({ sub, variant = 'full' }: { sub: Submission, variant?: 'full' | 'draft' }) {
        return (
            <Link
                href={sub.status === 'draft' ? `/submit?draft=${sub.id}` : `/report/${sub.id}`}
                className={cn(
                    "block vercel-card group transition-all",
                    variant === 'draft' ? "p-4" : "p-6"
                )}
            >
                <div className="flex justify-between items-center">
                    <div className="space-y-1">
                        <div className="text-[10px] font-mono text-gray-600 tracking-widest uppercase">
                            PKT_{sub.id.substring(0, 4).toUpperCase()}
                        </div>
                        <h3 className={cn(
                            "font-medium group-hover:text-white transition-colors",
                            variant === 'draft' ? "text-base" : "text-lg"
                        )}>
                            {sub.app_name || "Untitled App"}
                        </h3>
                        <div className="flex items-center gap-4 text-[10px] text-gray-500 font-mono uppercase tracking-wider">
                            <span className="text-white bg-white/5 px-1.5 py-0.5 rounded">
                                {variant === 'draft' ? 'Draft' : 'Full Review'}
                            </span>
                            <span>{formatDate(sub.created_at)}</span>
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        <StatusLight
                            status={mapStatus(sub.status)}
                            label={sub.status}
                            pulse={sub.status === 'analyzing' || sub.status === 'queued'}
                        />
                        <ArchiveButton submissionId={sub.id} />
                    </div>
                </div>
            </Link>
        )
    }

    return (
        <div className="container mx-auto px-6 max-w-5xl py-12">
            <header className="flex justify-between items-end mb-12">
                <div>
                    <h1 className="text-3xl font-bold tracking-tighter mb-2">Your Reviews</h1>
                    <p className="text-sm text-gray-500 font-light">
                        Monitor your iOS app compliance and rejection risks.
                    </p>
                </div>
                <div className="flex gap-4">
                    <Link href="/pricing" className="vercel-btn-secondary py-1.5 text-xs">
                        Buy Credits
                    </Link>
                    <Link href="/submit" className="vercel-btn-primary py-1.5 flex items-center gap-1.5 text-xs plus-hover-spin">
                        <Plus className="w-3.5 h-3.5" /> New Review
                    </Link>
                </div>
            </header>

            {(!submissions || (active.length === 0 && drafts.length === 0)) ? (
                <div className="vercel-card py-24 flex flex-col items-center text-center group">
                    <div className="mb-6 plus-hover-spin">
                        <Plus className="w-8 h-8 text-gray-500" />
                    </div>
                    <h2 className="text-xl font-medium mb-2">No Submissions Yet</h2>
                    <p className="text-gray-400 text-sm max-w-sm mb-8 font-light">
                        Upload your first iOS submission and Preflight will scan it against Apple&apos;s review guidelines.
                    </p>
                    <Link href="/submit" className="vercel-btn-primary flex items-center gap-2">
                        Begin Preflight Check <ArrowRight className="w-4 h-4" />
                    </Link>
                </div>
            ) : (
                <div className="space-y-12">
                    {/* Active Reviews */}
                    {active.length > 0 && (
                        <div className="space-y-4">
                            <h2 className="text-xs font-bold tracking-widest text-gray-500 uppercase">Active Reviews</h2>
                            <div className="space-y-4">
                                {active.map((sub) => (
                                    <SubmissionCard key={sub.id} sub={sub} />
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Drafts */}
                    {drafts.length > 0 && (
                        <div className="space-y-4">
                            <h2 className="text-xs font-bold tracking-widest text-gray-500 uppercase">Drafts</h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {drafts.map((sub) => (
                                    <SubmissionCard key={sub.id} sub={sub} variant="draft" />
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}
